---
title: 'OWID: Opioid Deaths Part 1'
author: "David Jackson"
date: "02/01/2021 8:00 PM/EST"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(scales)
library(plotly)
library(dplyr)
library(readr)
library(tidyr)
library(forcats)
library(skimr)
library(pracma) # Various moving averages
```

## Our world In Data (http://ourworldindata.org)

```{r}
opioid_rate <- read_csv("./DATA/death-rate-from-opioid-use.csv") %>%
  rename("Deaths" = "Opioid_deaths") %>% 
  rename("Country" = "Entity") %>%glimpse()
```

### Calc and Plot Yearly Death Rate

```{r}
opioid_yearly <- opioid_rate %>% group_by(Year) %>% summarise(
                        Rate = sum(Deaths),
                        Average = mean(Deaths)
)
```
```{r}
opioid_yearly %>% ggplot() + geom_line(aes(x=Year,y=Average)) +
  scale_y_continuous(labels=percent) + 
  labs(title="Worldwide Opioid Death Pecent by Year",y="Percent of Deaths")
```
```{r}
country_totals <- opioid_rate %>% group_by(Country) %>% summarise(
                        Rate = sum(Deaths),
                        Average = mean(Deaths))
```

### Calc and plot Top 10 Countries (Death Rate)

```{r}
country_totals %>% filter(Average >=3) %>% 
  ggplot() + geom_col(aes(x=reorder(Country,Average),y=Average)) + coord_flip() +
  scale_y_continuous(labels=percent) + labs(title="Top 10 Countries by Percent Increase")
```

