---
title: 'OWID: Drug Overdose Deaths'
author: "IllicitDavid Jackson"
date: "2/4/2021 06:15 PM/EST"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,error = FALSE)
library(ggplot2)
library(scales)
library(plotly)
library(dplyr)
library(readr)
library(tidyr)
library(forcats)
library(skimr)
library(pracma) # Various moving averages
```

# Drug Overdose Deaths: OUr World In Data (http://ourworldindata.org)
* Death rates from drug overdoses in the United States, measured as the number of deaths per 100,000 individuals (of all ages, not age-standardized).

```{r}
rm(list=ls())
overdose_deaths <- read_csv("./DATA/deaths-drug-overdoses.csv") %>%
  rename("Country" = "Entity") %>% filter(Country == "World")

```
```{r}
overdose_deaths %>%skim()
```
# Calculate Total Deaths by Drug and Year

```{r}
overdose_deaths$Total <- overdose_deaths$Opioid + overdose_deaths$Cocaine + overdose_deaths$Amphetamine + overdose_deaths$Other_drug


```

# Plot Total Drug Overdose Death by Year

```{r}
p0 <-overdose_deaths %>% ggplot(aes(x=Year,y=Total)) + geom_col() +
  scale_y_continuous(labels=comma) +
  labs(title="Worldwide Total Deaths Do To Drug Overdoses",y="Total Drug Overdose Deaths")
ggplotly(p0)
```

# Deaths by Drug and Year

```{r}
p1 <-overdose_deaths %>% ggplot(aes(x=Year,y=Opioid)) + geom_col() +
  scale_y_continuous(labels=comma) +
  labs(title="Worldwide Total Deaths Opioid Drug Overdoses",y="Total Drug Overdose Deaths")
ggplotly(p1)
```
```{r}
p2 <-overdose_deaths %>% ggplot(aes(x=Year,y=Cocaine)) + geom_col() +
  scale_y_continuous(labels=comma) +
  labs(title="Worldwide Total Deaths  Drug Cocaine Overdoses",y="Total Drug Overdose Deaths")
ggplotly(p2)
```
```{r}
p3 <- overdose_deaths %>% ggplot(aes(x=Year,y=Amphetamine)) + geom_col() +
  scale_y_continuous(labels=comma) +
  labs(title="Worldwide Total Deaths  Amphetamine Overdoses",y="Total Drug Overdose Deaths")
ggplotly(p3)
```
```{r}
p4 <- overdose_deaths %>% ggplot(aes(x=Year,y=Other_drug)) + geom_col() +
  scale_y_continuous(labels=comma) +
  labs(title="Worldwide Total Deaths Other Drugs Overdoses",y="Total Drug Overdose Deaths")
ggplotly(p4)
```